select * from customer limit 20

-- what is the total revenue generated by male vs female customers ?

select gender, sum(purchase_amount) as revenue
from customer
group by gender

-- which customers used discount but still purchase more than the average purchase amount ?

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

-- which are the top 5 products with the highest average rating ?

select item_purchased, round(avg(review_rating::numeric),2) as "Average Review Rating"
from customer
group by item_purchased 
order by avg(review_rating) desc
limit 5

-- compare the average purchase amount betweeen standard and Express shipping ?

select shipping_type,
round(avg(purchase_amount),2) as "Average Purchase Amount"
from customer
where shipping_type in ( 'Standard', 'Express')
group by shipping_type

-- Do subscribed customers spend more ? compare total revenue and avg spend between subscribers and non-subscribers.

select subscription_status,
count (customer_id) as total_customers,
round(avg(purchase_amount),2) as Average_spend,
round(sum(purchase_amount),2) as Total_revenue
from customer
group by subscription_status
order by Total_revenue, Average_spend desc

-- which 5 products have the highest percentage of purchases with discount applied ?

select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

-- segment customers into new, returning and loyal based on their total number of previous purchases, and show the count of each segment

with customer_type as (
select customer_id, previous_purchases, 
case
      when previous_purchases = 1 then 'New'
	  when previous_purchases between 2 and 10 then 'Returning'
	  else 'Loyal'
	  end as customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

-- what are the top 3 products within each category ?

with item_counts as (
select category,
item_purchased,
count (customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3

-- are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe ?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- what is the revenue contribution of each age group ?

select age_group,
sum(purchase_amount) as revenue_contribution
from customer
group by age_group
order by revenue_contribution desc








